-- Planning traces for player-behaviour analysis: the sequence of key planning actions in one game
-- (previews, line selections, confirmed stops, undo, finish/abandon), for logged-in players and anonymous guests.
-- Stored only; never used for scoring. Deleting a user keeps the anonymous trace but drops the link.
CREATE TABLE play_traces (
  id uuid PRIMARY KEY,                                   -- generated by the browser; repeated uploads are ignored
  user_id text REFERENCES "user"(id) ON DELETE SET NULL,
  anon_id uuid,                                          -- random per-browser id (guests and logged-in players alike)
  run_id uuid REFERENCES game_runs(id) ON DELETE SET NULL,
  round_id uuid REFERENCES run_rounds(id) ON DELETE SET NULL,
  mode text NOT NULL,
  city_id text NOT NULL,
  scenario jsonb,
  level_id text,
  origin jsonb,
  destination jsonb,
  outcome text NOT NULL CHECK (outcome IN ('finished', 'abandoned')),
  duration_ms integer CHECK (duration_ms >= 0),
  events jsonb NOT NULL CHECK (jsonb_typeof(events) = 'array'),
  route jsonb,
  summary jsonb,
  client jsonb,
  received_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX play_traces_received ON play_traces(received_at DESC);
CREATE INDEX play_traces_user ON play_traces(user_id, received_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX play_traces_anon ON play_traces(anon_id, received_at DESC);
CREATE INDEX play_traces_round ON play_traces(round_id) WHERE round_id IS NOT NULL;
COMMENT ON TABLE play_traces IS 'Per-game planning traces (key actions with timestamps) for behaviour analysis; not used for scoring.';
